version: 2.0
jobs:
 build:
   docker:
     - image: alpine:3.7
   steps:
     - run:
         name: The First Step
         command: |
           pwd
           ls -la
           ls -la ..
           find /root/project/ -type d -name 'projectEuler'
