version: 2.0
jobs:
 build:
   docker:
     - image: maven:3.3.9
   steps:
     - checkout
     - run:
         name: Run project's tests
         command: |
           cd projectEuler
           mvn -B verify
