version: 2.0
jobs:
 build:
   docker:
     - image: maven:3.3.9
   #working_directory: ~/ProjectEuler/
   steps:
     - run:
         name: Run project's tests
         command: |
           pwd
           ls -la
           find . -type f -name 'pom.xml'
