version: 2.0
jobs:
 build:
   docker:
     - image: alpine:3.7
   working_directory: ~/ProjectEuler/projectEuler
   steps:
     - run:
         name: Run project's tests
         command: |
           apt-get install maven
           mvn -B verify
